### ISSUE TITLE
GO sync package

### ISSUE THREAD

**Issue by hoangmit** [rgalanakis/goless#40]
Do you intend to implement some GO standard packages?

For example, "sync" package is quite useful. It is more efficient to implement if you know the goless' back-end.

**Comment by rgalanakis** [comment]
No, I do not plan to implement them, but would not be opposed to PRs. However I am not sure the underlying Stackless and gevent backends have those sorts of `sync` primitives.
Check out https://github.com/rgalanakis/goless/blob/master/goless/backends.py, you can add implementation-specific code there. Then you'd expose it with a `goless/sync.py` file, something like that.

Closing, but feel free to ask more questions or open a PR.
